name: update-liquid-templates-production
run-name: Update liquid templates for deployment to partner
# We run this action when a PR is closed and merged into the main branch
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  check-deploy-to-partner-label:
    runs-on: ubuntu-latest
    outputs:
      has_partner_deployment_label: ${{ steps.haslabel.outputs.labeled-3-deploy-to-partner }}
    steps:
      - name: Checkout Repository - Fetch all history for all tags and branches
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Labeled to partner deployment
        id: haslabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: "3-deploy-to-partner"

  check-changed-templates:
    runs-on: ubuntu-latest
    outputs:
      changed_templates: ${{ steps.templates_changed.outputs.changed_templates }}
    steps:
      - name: Checkout Repository - Fetch all history for all tags and branches
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Get changed liquid files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          since_last_remote_commit: false
          dir_names: false
          ref: 'main'
          files: |
            **/**.{liquid,yml,yaml,json}
      - name: Filter templates changed
        id: templates_changed
        run: |
          pattern="(?:reconciliation_texts|shared_parts|export_files|account_templates)/([^/]+)/"
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          if [ -n "$changed_files" ]; then
            filtered_names=($(printf "%s\n" "$changed_files" | grep -oP "$pattern" || true))
            if [ $? -ne 0 ]; then
              echo "No files match the pattern"
              changed_templates=()
            else
              # Remove the trailing "/" from the extracted names
              filtered_names=("${filtered_names[@]%/}")
              # Remove duplicates
              changed_templates=($(printf "%s\n" "${filtered_names[@]}" | sort -u))
            fi
          else
            echo "No changed files"
            changed_templates=()
          fi
          # Store outputs
          if [ ${#changed_templates[@]} -eq 0 ]; then
            echo "changed_templates=[]" >> $GITHUB_OUTPUT
          else
            echo "changed_templates=${changed_templates[*]}" >> $GITHUB_OUTPUT
            # Print the templates names
            for name in "${changed_templates[@]}"; do
              echo "$name"
            done
          fi
          exit 0

  run-tests:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
    needs: check-deploy-to-partner-label
